### ISSUE TITLE
Who is using the AST feature?

### ISSUE THREAD

**Issue by reox** [androguard/androguard#753]
Does anyone uses the AST feature of thje decompiler, i.e. this one:
```
from pprint import pprint
from androguard.decompiler.dad.decompile import DvMethod
for method in dx.get_methods():
    if method.is_external():
        continue
    dv = DvMethod(method)
    dv.process(doAST=True)
    pprint(dv.get_ast())
```

I would really like to see a usecase for this and some code how it is actually used.
If you have one, please post it here!

**Comment by reox** [comment]
@Storyyeller are you the author of the AST?
I would be glad to know if the format you used for the AST nodes is some standard format which can be used by other tools as well.

**Comment by krnick** [comment]
>androguard/decompiler/dad/decompile.py", line 92, in __init__
>self.start_block = next(methanalysis.get_basic_blocks().get(), None)
>AttributeError: 'MethodClassAnalysis' object has no attribute 'get_basic_blocks'

Just run the above code to test, got this kind of error.

**Comment by reox** [comment]
ah yeah... please run with the latest master! I merged MethodClassAnalysis and MethodAnalysis

**Comment by Storyyeller** [comment]
I added it for an internal tool I worked on while I was at Google. There's no standard format, I just did whatever was most convenient at the time.

That being said, I think outputting ASTs is generally a lot more useful than text if you're going to display it in a tool. Among other things, it allows you to do syntax highlighting without an error-prone reparse of the decompiled source code. And it gives you built-in support for cross referencing and renaming identifiers, information which is lost when you output text source code.

**Comment by subho007** [comment]
I tried using the AST to crossreference the source, but it has always been a challenge for me to cross-reference between `get_ast()` and `get_source()` 😞 

Any example you guys might have @reox @Storyyeller ?

**Comment by lxstart1024** [comment]
> ah yeah... please run with the latest master! I merged MethodClassAnalysis and MethodAnalysis

I am new to using androguard, currently using the version 3.3.5 still have the error:
self.start_block = next(methanalysis.get_basic_blocks().get(), None)
AttributeError: 'MethodClassAnalysis' object has no attribute 'get_basic_blocks'
